### ISSUE TITLE
Setup on Heroku

### ISSUE THREAD

**Issue by harshcrop** [lolibrarian/NYPL-Emoji-Bot#13]
Facing problem setup Bot On Heroku 

#Error 

Starting Twitter reply process
/app/node_modules/twit/lib/auth.js:25
      throw new Error('config must provide ' + requirement)
      ^
Error: config must provide consumer_key
    at /app/node_modules/twit/lib/auth.js:25:13
    at Array.forEach (native)
    at new Auth (/app/node_modules/twit/lib/auth.js:23:12)
    at Object.Twitter (/app/node_modules/twit/lib/twitter.js:34:15)
    at Object.<anonymous> (/app/src/twitter.js:5:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

This is the error I get.
Help Needed!

**Comment by toddmazierski** [comment]
Hi, @harshcrop. It looks like the [environment variables the app needs](https://github.com/lolibrarian/NYPL-Emoji-Bot/blob/master/.env.example) have not been [set in Heroku](https://devcenter.heroku.com/articles/config-vars). Hope that's helpful!
